In [7]:
########Ans 1##########
from bs4 import BeautifulSoup
import requests
def Header(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    heading_tags = ["h1", "h2", "h3"]
    table=soup.find_all(heading_tags)
    for i in table:
        print(i)
Header("https://en.wikipedia.org/wiki/Main_Page")

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none"><span class="mw-page-title-main">Main Page</span></h1>
<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>
<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>
<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>
<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>
<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>
<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>
<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>
<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>
<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>
<h2>Navigation menu</h2>
<h3 class="vector-menu-heading" id="p-personal-label">
		<span class="vector-menu-heading-label">Personal tools</span>
	</h3>
<h3 class="vector-menu-heading" id="p-namespaces-label">
		<span class="vector-menu-heading-label">Namespaces</span>
	</h3>
<h3 class="vector-menu-heading" id="p-views-label">
		<span class="vector-menu-heading-label">Views</span>
	</h3>
<h3>
				<label for="searchInput">Search</label>
			</h3>
<h3 class="vector-menu-heading" id="p-navigation-label">
		<span class="vector-menu-heading-label">Navigation</span>
	</h3>
<h3 class="vector-menu-heading" id="p-interaction-label">
		<span class="vector-menu-heading-label">Contribute</span>
	</h3>
<h3 class="vector-menu-heading" id="p-tb-label">
		<span class="vector-menu-heading-label">Tools</span>
	</h3>
<h3 class="vector-menu-heading" id="p-coll-print_export-label">
		<span class="vector-menu-heading-label">Print/export</span>
	</h3>
<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
		<span class="vector-menu-heading-label">In other projects</span>
	</h3>
<h3 class="vector-menu-heading" id="p-lang-label">
		<span class="vector-menu-heading-label">Languages</span>
	</h3>

In [8]:
#############Ans 2################
import re
import pandas as pd
def ImdbTop100(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    movies = soup.select('td.titleColumn')
    crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
    ratings = [b.attrs.get('data-value') for b in soup.select('td.posterColumn span[name=ir]')]
    li = []

    for index in range(0, len(movies)):


        movie_string = movies[index].get_text()
        movie = (' '.join(movie_string.split()).replace('.', ''))
        movie_title = movie[len(str(index))+1:-7]
        year = re.search('\((.*?)\)', movie_string).group(1)
        place = movie[:len(str(index))-(len(movie))]
        data = {"place": place,
                "movie_title": movie_title,
                "rating": ratings[index],
                "year": year,
                "star_cast": crew[index],
                }
        li.append(data)
    for movie in li[:100]:
        print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
            ') -', 'Starring:', movie['star_cast'], movie['rating'])
    df = pd.DataFrame(li[:100])
ImdbTop100('http://www.imdb.com/chart/top')

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman 9.234847906865825
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino 9.156528250725977
3 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger 8.987540445476439
4 - The Godfather Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro 8.984524283540464
5 - 12 Angry Men (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb 8.949342812177804
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes 8.93654347164011
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen 8.923859845676894
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman 8.849586391735189
9 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.805152942561534
1 -  Il buono, il brutto, il cattivo (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach 8.792442638273828
11 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright 8.767905032961899
12 - Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton 8.749244851990621
13 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt 8.733148552451157
14 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.729930141739255
15 - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford 8.70108195706465
16 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne 8.670441806327291
17 - Goodfellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta 8.65252252416167
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher 8.640332304859665
19 - Se7en (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt 8.604400862116313
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura 8.59898111088211
21 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed 8.596781956433256
22 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins 8.588323555413572
23 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino 8.579156176292772
24 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon 8.578689602146445
25 - La vita è bella (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi 8.566612799940453
26 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan 8.56097885942917
27 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway 8.560101143643129
28 - Star Wars (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford 8.552727064045339
29 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.536426423692413
30 - Back to the Future (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd 8.518135912247386
31 - Sen to Chihiro no kamikakushi (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette 8.51528355654495
32 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh 8.508224334671338
33 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann 8.50544125563894
34 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman 8.498471381887684
35 - Gisaengchung (2019) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Sun-kyun Lee 8.496576893659089
36 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons 8.488478749775144
37 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix 8.486362419624285
38 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong 8.48384349208867
39 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon 8.475696295616377
40 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne 8.47456332672968
41 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman 8.468582603841243
42 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman 8.464315794362403
43 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons 8.46253500318824
44 - The Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy 8.453714884543789
45 - Hotaru no haka (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi 8.450531729606864
46 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama 8.45052875857512
47 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.448864170669225
48 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson 8.44640491601287
49 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly 8.437149537856108
50 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt 8.434981951075788
51 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill 8.434040383898898
52 - Nuovo Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale 8.43134695449173
53 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando 8.42489935219282
54 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss 8.424241905271387
55 - Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen 8.410707510326038
56 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz 8.40444469087964
57 - WALL·E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight 8.39350470481878
58 - The Lives of Others (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck 8.38574242238745
59 - Sunset Blvd (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson 8.38295214343644
60 - Paths of Glory (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker 8.371623553662396
61 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall 8.36705084704091
62 - Top Gun: Maverick (2022) - Starring: Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly 8.366515379633018
63 - The Great Dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.365970960991337
64 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich 8.35916841833272
65 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth 8.358935509830252
66 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn 8.344500363903393
67 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening 8.335856625587864
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott 8.332094138508012
69 - Spider-Man: Into the Spider-Verse (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson 8.331440730971675
70 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy 8.328093530358089
71 - Oldeuboi (2003) - Starring: Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae 8.320165683438264
72 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro 8.317577605971232
73 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce 8.3159388777187
74 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau 8.31530135999906
75 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen 8.314983269999981
76 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal 8.313382287666947
77 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger 8.313133540044424
78 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer 8.31269859346941
79 - Mononoke-hime (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida 8.30357933214181
80 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans 8.303213153786555
81 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods 8.297952902798405
82 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon 8.288210670500597
83 - Kimi no na wa (2016) - Starring: Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi 8.27764983105625
84 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto 8.275712300509602
85 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen 8.275539624174117
86 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor 8.273572406976383
87 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan 8.271293383971589
88 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford 8.26698060585584
89 - Tengoku to jigoku (1963) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada 8.266684635013814
90 - 2001: A Space Odyssey (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood 8.264119736858836
91 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet 8.263417436122825
92 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth 8.26308392143274
93 - Capharnaüm (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw 8.25978435908464
94 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness 8.25597293326931
95 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten 8.255867078904707
96 - Jagten (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen 8.255857312243643
97 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann 8.254173954935787
98 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint 8.252034465117456
99 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova 8.248267391239667
10 -  Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak 8.246667622161409

In [2]:
############Ans 3######################
def ImdbIndianTop100(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    results=soup.find_all("td")
    l=[]
    for i in range(1,len(results),5):
        if i==len(results)-1:
            break
        else:
            name=results[i].text.strip().split(".")[-1].strip().split("\n")[0]
            year=results[i].text.strip().split(".")[-1].strip().split("\n")[-1][9:13]
            rating=results[i+1].text.strip()
        l.append([name,year,rating])
        if len(l)==100:
            break
    for i in range(len(l)):
        print(str(i+1)+" "+l[i][0]+" "+l[i][1]+" "+l[i][2])
    df = pd.DataFrame(l)
    df.columns=["Movie Name","Year","IMDB Rating"]
    print(df)
            
ImdbIndianTop100("https://www.imdb.com/india/top-rated-indian-movies/?sort=ir,desc&mode=simple&page=1")

1 Rocketry: The Nambi Effect 2022 8.5
2 Anbe Sivam 2003 8.4
3 Golmaal 1979 8.4
4 Nayakan 1987 8.4
5 Jai Bhim 2021 8.4
6 Pariyerum Perumal 2018 8.4
7 3 Idiots 2009 8.4
8 Apur Sansar 1959 8.3
9 Manichitrathazhu 1993 8.3
10 777 Charlie 2022 8.3
11 Kumbalangi Nights 2019 8.3
12 Black Friday 2004 8.3
13 C/o Kancharapalem 2018 8.3
14 Soorarai Pottru 2020 8.3
15 #Home 2021 8.3
16 Taare Zameen Par 2007 8.3
17 Kireedam 1989 8.3
18 Dangal 2016 8.3
19 Kaithi 2019 8.3
20 Jersey 2019 8.3
21 96 2018 8.2
22 Asuran 2019 8.2
23 Thevar Magan 1992 8.2
24 Visaaranai 2015 8.2
25 Sarpatta Parambarai 2021 8.2
26 Natsamrat 2016 8.2
27 Thalapathi 1991 8.2
28 Pather Panchali 1955 8.2
29 Drishyam 2 2021 8.2
30 Nadodikkattu 1987 8.2
31 Thani Oruvan 2015 8.2
32 Sardar Udham 2021 8.2
33 Vada Chennai 2018 8.2
34 Aparajito 1956 8.2
35 Jaane Bhi Do Yaaro 1983 8.2
36 Khosla Ka Ghosla! 2006 8.2
37 Drishyam 2013 8.2
38 Peranbu 2018 8.1
39 Anniyan 2005 8.1
40 Chupke Chupke 1975 8.1
41 Mahanati 2018 8.1
42 Agent Sai Srinivasa Athreya 2019 8.1
43 Ratsasan 2018 8.1
44 Bangalore Days 2014 8.1
45 Satya 1998 8.1
46 Premam 2015 8.1
47 Super Deluxe 2019 8.1
48 Vikram 2022 8.1
49 Devasuram 1993 8.1
50 Gangs of Wasseypur 2012 8.1
51 Bhaag Milkha Bhaag 2013 8.1
52 Drishyam 2015 8.1
53 Aruvi 2016 8.1
54 Andhadhun 2018 8.1
55 Chithram 1988 8.1
56 Kannathil Muthamittal 2002 8.1
57 Guide 1965 8.1
58 Vikram Vedha 2017 8.1
59 Iruvar 1997 8.1
60 Sairat 2016 8.1
61 Shahid 2012 8.1
62 Tumbbad 2018 8.1
63 Zindagi Na Milegi Dobara 2011 8.1
64 Paan Singh Tomar 2012 8.1
65 Mudhalvan 1999 8.1
66 Chhichhore 2019 8.1
67 Spadikam 1995 8.1
68 Dhuruvangal Pathinaaru 2016 8.1
69 Swades: We, the People 2004 8.1
70 Chak De! India 2007 8.1
71 Pudhu Pettai 2006 8.1
72 Black 2005 8.1
73 Jo Jeeta Wohi Sikandar 1992 8.1
74 Papanasam 2015 8.1
75 Mandela 2021 8.1
76 Pyaasa 1957 8.1
77 Uri: The Surgical Strike 2019 8.1
78 (2003)  8.1
79 Article 15 2019 8.1
80 Soodhu Kavvum 2013 8.1
81 Queen 2013 8.0
82 Kaakkaa Muttai 2014 8.0
83 Talvar 2015 8.0
84 Lagaan: Once Upon a Time in India 2001 8.0
85 PK 2014 8.0
86 OMG: Oh My God! 2012 8.0
87 Jigarthanda 2014 8.0
88 Sarfarosh 1999 8.0
89 Hera Pheri 2000 8.0
90 Theeran Adhigaaram Ondru 2017 8.0
91 Udaan 2010 8.0
92 Barfi! 2012 8.0
93 Sholay 1975 8.0
94 Ustad Hotel 2012 8.0
95 The Legend of Bhagat Singh 2002 8.0
96 Angoor 1982 8.0
97 Baahubali 2: The Conclusion 2017 8.0
98 Virumandi 2004 8.0
99 Rang De Basanti 2006 8.0
100 Baasha 1995 8.0

NameError: name 'pd' is not defined

In [102]:
###########Ans 4####################
def President_of_India(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    temp=soup.find("ul",{'class':"listing cf"})
    results=temp.findAll("li")
    names=[]
    term=[]
    for i in range(len(results)):
        names.append(results[i].find("h3").text.split("(")[0])
        term.append(results[i].find("p").text.split("</span>")[0])
    for i in range(len(names)):
        print("Name: "+" "+names[i]+" "+term[i])
    
            
President_of_India("https://presidentofindia.nic.in/former-presidents.htm")

Name:  Shri Ram Nath Kovind  Term of Office: 25 July, 2017 to 25 July, 2022
Name:  Shri Pranab Mukherjee  Term of Office: 25 July, 2012 to 25 July, 2017
Name:  Smt Pratibha Devisingh Patil  Term of Office: 25 July, 2007 to 25 July, 2012
Name:  DR. A.P.J. Abdul Kalam  Term of Office: 25 July, 2002 to 25 July, 2007
Name:  Shri K. R. Narayanan  Term of Office: 25 July, 1997 to 25 July, 2002
Name:  Dr Shankar Dayal Sharma  Term of Office: 25 July, 1992 to 25 July, 1997
Name:  Shri R Venkataraman  Term of Office: 25 July, 1987 to 25 July, 1992
Name:  Giani Zail Singh  Term of Office: 25 July, 1982 to 25 July, 1987
Name:  Shri Neelam Sanjiva Reddy  Term of Office: 25 July, 1977 to 25 July, 1982
Name:  Dr. Fakhruddin Ali Ahmed  Term of Office: 24 August, 1974 to 11 February, 1977
Name:  Shri Varahagiri Venkata Giri  Term of Office: 3 May, 1969 to 20 July, 1969 and 24 August, 1969 to 24 August, 1974
Name:  Dr. Zakir Husain  Term of Office: 13 May, 1967 to 3 May, 1969
Name:  Dr. Sarvepalli Radhakrishnan  Term of Office: 13 May, 1962 to 13 May, 1967
Name:  Dr. Rajendra Prasad  Term of Office: 26 January, 1950 to 13 May, 1962

In [154]:
###########Ans 5####################
def ODIMenTeams(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    team=[]
    match=[]
    points=[]
    ratings=[]
    temp=soup.find("tr",{'class':"rankings-block__banner"})
    team1=temp.find("td",{'class':"rankings-block__banner--team-name"})
    team.append(team1.find("span",{'class':'u-hide-phablet'}).text)
    match.append(temp.find("td",{'rankings-block__banner--matches'}).text)
    points.append(temp.find("td",{'class':'rankings-block__banner--points'}).text)
    ratings.append(temp.find("td",{'class':'rankings-block__banner--rating u-text-right'}).text.strip())
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9):
        team1=temp[i].find("td",{'class':"table-body__cell rankings-table__team"})
        team.append(team1.find("span",{'class':'u-hide-phablet'}).text)
        match.append(temp[i].findAll("td",{'table-body__cell u-center-text'})[0].text)
        points.append(temp[i].findAll("td",{'class':'table-body__cell u-center-text'})[1].text)
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(team[i]+" "+match[i]+" "+points[i]+" "+ratings[i])

ODIMenTeams("https://www.icc-cricket.com/rankings/mens/team-rankings/odi")

New Zealand 19 2,355 124
England 27 3,226 119
India 31 3,447 111
Pakistan 22 2,354 107
Australia 25 2,548 102
South Africa 21 2,111 101
Bangladesh 30 2,753 92
Sri Lanka 29 2,658 92
West Indies 41 2,902 71
Afghanistan 18 1,238 69

In [41]:
def ODIBatsMen(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    player=[]
    team=[]
    ratings=[]
    temp=soup.find("div",{'class':"rankings-block__top-player"})
    player.append(temp.find("div",{'class':"rankings-block__banner--name"}).text)
    team.append(temp.find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[0].strip())
    ratings.append(temp.find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[28])
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9):
        player.append(temp[i].find("td",{'class':"table-body__cell name"}).text.strip())
        team.append(temp[i].find("td",{'class':"table-body__cell nationality-logo"}).text.strip())
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(player[i]+" "+team[i]+" "+ratings[i])

ODIBatsMen("https://www.icc-cricket.com/rankings/mens/player-rankings/odi")

Babar Azam PAK 890
Rassie van der Dussen SA 789
Quinton de Kock SA 784
Imam-ul-Haq PAK 779
Virat Kohli IND 744
Rohit Sharma IND 740
David Warner AUS 739
Jonny Bairstow ENG 732
Ross Taylor NZ 722
Aaron Finch AUS 706

In [46]:
def ODIBowlMen(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    player=[]
    team=[]
    ratings=[]
    temp=soup.findAll("div",{'class':"rankings-block__top-player"})
    player.append(temp[1].find("div",{'class':"rankings-block__banner--name"}).text)
    team.append(temp[1].find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[0].strip())
    ratings.append(temp[1].find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[28])
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9,18):
        player.append(temp[i].find("td",{'class':"table-body__cell name"}).text.strip())
        team.append(temp[i].find("td",{'class':"table-body__cell nationality-logo"}).text.strip())
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(player[i]+" "+team[i]+" "+ratings[i])

ODIBowlMen("https://www.icc-cricket.com/rankings/mens/player-rankings/odi")

Trent Boult NZ 720
Josh Hazlewood AUS 678
Mujeeb Ur Rahman AFG 676
Jasprit Bumrah IND 662
Shaheen Afridi PAK 661
Mohammad Nabi AFG 657
Mehedi Hasan BAN 655
Rashid Khan AFG 651
Matt Henry NZ 644
Mustafizur Rahman BAN 640

In [47]:
###########Ans 6###############
def ODIWomenTeams(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    team=[]
    match=[]
    points=[]
    ratings=[]
    temp=soup.find("tr",{'class':"rankings-block__banner"})
    team1=temp.find("td",{'class':"rankings-block__banner--team-name"})
    team.append(team1.find("span",{'class':'u-hide-phablet'}).text)
    match.append(temp.find("td",{'rankings-block__banner--matches'}).text)
    points.append(temp.find("td",{'class':'rankings-block__banner--points'}).text)
    ratings.append(temp.find("td",{'class':'rankings-block__banner--rating u-text-right'}).text.strip())
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9):
        team1=temp[i].find("td",{'class':"table-body__cell rankings-table__team"})
        team.append(team1.find("span",{'class':'u-hide-phablet'}).text)
        match.append(temp[i].findAll("td",{'table-body__cell u-center-text'})[0].text)
        points.append(temp[i].findAll("td",{'class':'table-body__cell u-center-text'})[1].text)
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(team[i]+" "+match[i]+" "+points[i]+" "+ratings[i])

ODIWomenTeams("https://www.icc-cricket.com/rankings/womens/team-rankings/odi")

Australia 29 4,837 167
England 33 4,046 123
South Africa 35 4,157 119
India 32 3,219 101
New Zealand 31 3,019 97
West Indies 30 2,768 92
Bangladesh 12 930 78
Pakistan 30 1,962 65
Ireland 11 516 47
Sri Lanka 11 495 45

In [50]:
def ODIBatsWomen(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    player=[]
    team=[]
    ratings=[]
    temp=soup.find("div",{'class':"rankings-block__top-player"})
    player.append(temp.find("div",{'class':"rankings-block__banner--name"}).text)
    team.append(temp.find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[0].strip())
    ratings.append(temp.find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[28])
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9):
        player.append(temp[i].find("td",{'class':"table-body__cell name"}).text.strip())
        team.append(temp[i].find("td",{'class':"table-body__cell nationality-logo"}).text.strip())
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(player[i]+" "+team[i]+" "+ratings[i])

ODIBatsWomen("https://www.icc-cricket.com/rankings/womens/player-rankings/odi")

Alyssa Healy AUS 785
Beth Mooney AUS 749
Natalie Sciver ENG 747
Laura Wolvaardt SA 732
Meg Lanning AUS 710
Rachael Haynes AUS 701
Amy Satterthwaite NZ 681
Tammy Beaumont ENG 667
Chamari Athapaththu SL 655
Smriti Mandhana IND 649

In [51]:
def ODIBowlWomen(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,'html5lib')
    player=[]
    team=[]
    ratings=[]
    temp=soup.findAll("div",{'class':"rankings-block__top-player"})
    player.append(temp[1].find("div",{'class':"rankings-block__banner--name"}).text)
    team.append(temp[1].find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[0].strip())
    ratings.append(temp[1].find("div",{'class':'rankings-block__banner--nationality'}).text.strip().split(" ")[28])
    temp=soup.findAll("tr",{"class":"table-body"})
    for i in range(9,18):
        player.append(temp[i].find("td",{'class':"table-body__cell name"}).text.strip())
        team.append(temp[i].find("td",{'class':"table-body__cell nationality-logo"}).text.strip())
        ratings.append(temp[i].find("td",{'class':'table-body__cell u-text-right rating'}).text.strip())
    for i in range(len(team)):
        print(player[i]+" "+team[i]+" "+ratings[i])

ODIBowlWomen("https://www.icc-cricket.com/rankings/womens/player-rankings/odi")

Sophie Ecclestone ENG 761
Jess Jonassen AUS 725
Megan Schutt AUS 722
Shabnim Ismail SA 722
Jhulan Goswami IND 644
Ayabonga Khaka SA 634
Rajeshwari Gayakwad IND 613
Hayley Matthews WI 612
Katherine Brunt ENG 601
Marizanne Kapp SA 598

In [64]:
def Headline(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,"html5lib")
    temp=soup.find("ul",{"class":"LatestNews-list"})
    results=temp.findAll("li","LatestNews-item")
    headline=[]
    time=[]
    links=[]
    for i in range(len(results)):
        headline.append(results[i].find("a",{"class":"LatestNews-headline"}).text.strip())
        time.append(results[i].find("time",{"class":"LatestNews-timestamp"}).text.strip())
        l=soup.find("a",{"class":"LatestNews-headline"})
        links.append(l.get("href"))
    for i in range(len(headline)):
        print(headline[i]+"    "+time[i]+"    "+links[i])
    
Headline("https://www.cnbc.com/world/?region=world%20:")

Meet the 31-year-old living in a building of retirees in Naples, Florida    50 Min Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Bed Bath & Beyond CFO Gustavo Arnal fell to his death in Manhattan    2 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
48% of people talk to their plants and it might be making them happier    4 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
'Life-changing' 'sleeper hit:' New student loan plan slashes payments, interest    4 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Stocks are stormy into September. Assessing which safe haven is right for you    6 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
These are the Street’s favorite defensive stocks amid September’s bad reputation    6 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
This $310,000 electric RV has heated floors and Elon Musk's internet—look inside    6 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Mark Zuckerberg: Social media is for 'building relationships,' not scrolling    6 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
How electric vehicle manufacturing could shrink the Midwestern job market    7 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Here's how student loan forgiveness could impact your credit score    7 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Airlines revamp in-flight menus, from vegan meatballs to ice cream sundaes    8 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Over 25 million watched 'The Lord of the Rings: The Rings of Power,' Amazon says    21 Hours Ago    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
New study: These are the top 10 best cities in the U.S. for Gen Zers    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
You can still get at-home Covid tests for free—here's how    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
France says imposing a price cap on Russian oil will be difficult    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
NASA delays Artemis moon mission after second launch attempt halted    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
How this 28-year old makes $189,000 a year off 7 income streams: ‘I work just 3.5 days a week’    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Trump SPAC's survival at stake in Digital World shareholder vote on merger delay    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Analysts are raving about these top stocks they say are firing on all cylinders    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
The housing tech revolution boosted by the pandemic continues. How to play it    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
This couple had an Amazon-themed wedding to celebrate their love of e-commerce    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Here's how much the typical Gen Z worker makes in every U.S. state    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
New omicron boosters are available, but it's unclear how effective they will be    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
These charts show how the 2022 box office sizzled, then fizzled    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Inflation Reduction Act: Here's when you may claim climate tax breaks, rebates    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Sen. Lindsey Graham says he was stating the obvious with Trump riots claim    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
EU economics chief says bloc is ready to react over halted Russian gas supplies    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
EU energy chief urges China and India to support a price cap on Russian oil    September 3, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
Trump pick in key Michigan race threatened to kill family: Court record    September 2, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html
How 'quiet quitting' became the next phase of the Great Resignation    September 2, 2022    https://www.cnbc.com/2022/09/04/this-31-year-old-lives-in-a-retirement-community-in-florida-.html

In [67]:
###########Ans 8###############
def ResearchPaper(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,"html5lib")
    temp=soup.find("ul",{"class":"sc-9zxyh7-0 ffmPq"})
    results=temp.findAll("li","sc-9zxyh7-1 sc-9zxyh7-2 exAXfr jQmQZp")
    title=[]
    author=[]
    date=[]
    links=[]
    for i in range(len(results)):
        title.append(results[i].find("h2",{"class":"sc-1qrq3sd-1 MKjKb sc-1nmom32-0 sc-1nmom32-1 hqhUYH ebTA-dR"}).text.strip())
        author.append(results[i].find("span",{"class":"sc-1w3fpd7-0 pgLAT"}).text.strip())
        date.append(results[i].find("span",{"class":"sc-1thf9ly-2 bKddwo"}).text)
        l=soup.find("a","sc-5smygv-0 nrDZj")
        links.append(l.get("href"))
    for i in range(len(title)):
        print(title[i]+"    "+author[i]+"    "+date[i]+"    "+links[i])
    
    
ResearchPaper("https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles")

Reward is enough    Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S.    October 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Making sense of raw input    Evans, Richard, Bošnjak, Matko and 5 more    October 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Law and logic: A review from an argumentation perspective    Prakken, Henry, Sartor, Giovanni    October 2015    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Creativity and artificial intelligence    Boden, Margaret A.    August 1998    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Artificial cognition for social human–robot interaction: An implementation    Lemaignan, Séverin, Warnier, Mathieu and 3 more    June 2017    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Explanation in artificial intelligence: Insights from the social sciences    Miller, Tim    February 2019    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Making sense of sensory input    Evans, Richard, Hernández-Orallo, José and 3 more    April 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Conflict-based search for optimal multi-agent pathfinding    Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R.    February 2015    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning    Sutton, Richard S., Precup, Doina, Singh, Satinder    August 1999    https://www.sciencedirect.com/science/article/pii/S0004370221000862
The Hanabi challenge: A new frontier for AI research    Bard, Nolan, Foerster, Jakob N. and 13 more    March 2020    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Evaluating XAI: A comparison of rule-based and example-based explanations    van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark    February 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Argumentation in artificial intelligence    Bench-Capon, T.J.M., Dunne, Paul E.    October 2007    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Algorithms for computing strategies in two-player simultaneous move games    Bošanský, Branislav, Lisý, Viliam and 3 more    August 2016    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Multiple object tracking: A literature review    Luo, Wenhan, Xing, Junliang and 4 more    April 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Selection of relevant features and examples in machine learning    Blum, Avrim L., Langley, Pat    December 1997    https://www.sciencedirect.com/science/article/pii/S0004370221000862
A survey of inverse reinforcement learning: Challenges, methods and progress    Arora, Saurabh, Doshi, Prashant    August 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Explaining individual predictions when features are dependent: More accurate approximations to Shapley values    Aas, Kjersti, Jullum, Martin, Løland, Anders    September 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
A review of possible effects of cognitive biases on interpretation of rule-based machine learning models    Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes    June 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Integrating social power into the decision-making of cognitive agents    Pereira, Gonçalo, Prada, Rui, Santos, Pedro A.    December 2016    https://www.sciencedirect.com/science/article/pii/S0004370221000862
“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems    Riveiro, Maria, Thill, Serge    September 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies    Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T.    May 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Algorithm runtime prediction: Methods & evaluation    Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin    January 2014    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Wrappers for feature subset selection    Kohavi, Ron, John, George H.    December 1997    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics    Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna    October 2021    https://www.sciencedirect.com/science/article/pii/S0004370221000862
Quantum computation, quantum theory and AI    Ying, Mingsheng    February 2010    https://www.sciencedirect.com/science/article/pii/S0004370221000862

In [45]:
############Ans 9#############
def dineIn(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,"html5lib")
    result=soup.find("div",{"class":"restnt-card-wrap-new"})
    temp=result.findAll("div",{"class":"restnt-card restaurant"})
    rest=[]
    cuisine=[]
    c=[]
    loc=[]
    l=""
    ratings=[]
    imgurl=[]
    for i in range(len(temp)):
        rest.append(temp[i].find("div",{"class":"restnt-info cursor"}).text)
        cus=temp[i].find("span",{"class":"double-line-ellipsis"})
        for j in cus.findAll("a"):
            c.append(j.text)
        cuisine.append(c)
        c=[]
        lo=temp[i].find("div",{"class":"restnt-loc ellipsis"})
        for j in lo.findAll("a"):
            l+=j.text+", "
        loc.append(l)
        ratings.append(temp[i].find("div",{"class":"restnt-rating rating-4"}).text)
        im=temp[i].find('img',{"class":"no-img"})
        imgurl.append(im.get('data-src'))
        #l=soup.find("a","sc-5smygv-0 nrDZj")
        #links.append(l.get("href"))
    for i in range(len(rest)):
        print(rest[i])
        print(cuisine[i])
        print(loc[i])
        print(ratings[i])
        print(imgurl[i])
        print("\n")
    
dineIn("https://www.dineout.co.in/delhi-restaurants/buffet-special")

Castle BarbequeConnaught Place, Central Delhi
['Chinese', 'North Indian']
Connaught Place, Central Delhi,
4.1
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/8/k/b/p86792-16062953735fbe1f4d3fb7e.jpg?tr=tr:n-medium


Jungle Jamboree3CS Mall,Lajpat Nagar - 3, South Delhi
['North Indian', 'Asian', 'Italian']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi,
3.9
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/p/m/p59633-166088382462ff137009010.jpg?tr=tr:n-medium


Castle BarbequePacific Mall,Tagore Garden, West Delhi
['Chinese', 'North Indian']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi,
3.9
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/j/o/p38113-15959192065f1fcb666130c.jpg?tr=tr:n-medium


Cafe KnoshThe Leela Ambience Convention Hotel,Shahdara, East Delhi
['Italian', 'Continental']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi,
4.3
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/4/p/m/p406-15438184745c04ccea491bc.jpg?tr=tr:n-medium


The Barbeque CompanyGardens Galleria,Sector 38A, Noida
['North Indian', 'Chinese']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi, Gardens Galleria,, Sector 38A, Noida,
4
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/7/p/k/p79307-16051787755fad1597f2bf9.jpg?tr=tr:n-medium


India GrillHilton Garden Inn,Saket, South Delhi
['North Indian', 'Italian']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi, Gardens Galleria,, Sector 38A, Noida, Hilton Garden Inn,, Saket, South Delhi,
3.9
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/2/v/t/p2687-1482477169585cce712b90f.jpg?tr=tr:n-medium


Delhi BarbequeTaurus Sarovar Portico,Mahipalpur, South Delhi
['North Indian']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi, Gardens Galleria,, Sector 38A, Noida, Hilton Garden Inn,, Saket, South Delhi, Taurus Sarovar Portico,, Mahipalpur, South Delhi,
3.7
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/d/i/p52501-1661855212630de5eceb6d2.jpg?tr=tr:n-medium


The Monarch - Bar Be Que VillageIndirapuram Habitat Centre,Indirapuram, Ghaziabad
['North Indian']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi, Gardens Galleria,, Sector 38A, Noida, Hilton Garden Inn,, Saket, South Delhi, Taurus Sarovar Portico,, Mahipalpur, South Delhi, Indirapuram Habitat Centre,, Indirapuram, Ghaziabad,
3.8
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/3/n/o/p34822-15599107305cfa594a13c24.jpg?tr=tr:n-medium


Indian Grill RoomSuncity Business Tower,Golf Course Road, Gurgaon
['North Indian', 'Mughlai']
Connaught Place, Central Delhi, 3CS Mall,, Lajpat Nagar - 3, South Delhi, Pacific Mall,, Tagore Garden, West Delhi, The Leela Ambience Convention Hotel,, Shahdara, East Delhi, Gardens Galleria,, Sector 38A, Noida, Hilton Garden Inn,, Saket, South Delhi, Taurus Sarovar Portico,, Mahipalpur, South Delhi, Indirapuram Habitat Centre,, Indirapuram, Ghaziabad, Suncity Business Tower,, Golf Course Road, Gurgaon,
4.3
https://im1.dineout.co.in/images/uploads/restaurant/sharpen/5/y/f/p549-165000147262590640c0afc.jpg?tr=tr:n-medium

In [62]:
###########Ans 10############
def scholar(url):
    r=requests.get(url)
    soup=BeautifulSoup(r.content,"html5lib")
    rank=list(soup.findAll("td",{"class":"gsc_mvt_p"}))
    publication=list(soup.findAll("td",{"class":"gsc_mvt_t"}))
    h5_index=list(soup.findAll("a",{"class":"gs_ibl gsc_mp_anchor"}))
    h5_median=list(soup.findAll("span",{"class":"gs_ibl gsc_mp_anchor"}))
    r=[]
    p=[]
    h5i=[]
    h5m=[]
    for i in range(len(rank)):
        r.append(rank[i].text)
        p.append(publication[i].text)
        h5i.append(h5_index[i].text)
        h5m.append(h5_median[i].text)
    for i in range(len(r)):
        print(str(r[i])+" "+str(p[i])+" "+str(h5i[i])+" "+str(h5m[i]))
    
scholar("https://scholar.google.com/citations?view_op=top_venues&hl=en")

1. Nature 444 667
2. The New England Journal of Medicine 432 780
3. Science 401 614
4. IEEE/CVF Conference on Computer Vision and Pattern Recognition 389 627
5. The Lancet 354 635
6. Advanced Materials 312 418
7. Nature Communications 307 428
8. Cell 300 505
9. International Conference on Learning Representations 286 533
10. Neural Information Processing Systems 278 436
11. JAMA 267 425
12. Chemical Reviews 265 444
13. Proceedings of the National Academy of Sciences 256 364
14. Angewandte Chemie 245 332
15. Chemical Society Reviews 244 386
16. Journal of the American Chemical Society 242 344
17. IEEE/CVF International Conference on Computer Vision 239 415
18. Nucleic Acids Research 238 550
19. International Conference on Machine Learning 237 421
20. Nature Medicine 235 389
21. Renewable and Sustainable Energy Reviews 227 324
22. Science of The Total Environment 225 311
23. Advanced Energy Materials 220 300
24. Journal of Clinical Oncology 213 315
25. ACS Nano 211 277
26. Journal of Cleaner Production 211 273
27. Advanced Functional Materials 210 280
28. Physical Review Letters 207 294
29. Scientific Reports 206 274
30. The Lancet Oncology 202 329
31. Energy & Environmental Science 202 290
32. IEEE Access 200 303
33. PLoS ONE 198 278
34. Science Advances 197 294
35. Journal of the American College of Cardiology 195 276
36. Applied Catalysis B: Environmental 192 246
37. Nature Genetics 191 297
38. BMJ 190 307
39. Circulation 189 301
40. European Conference on Computer Vision 186 321
41. International Journal of Molecular Sciences 183 253
42. Nature Materials 181 265
43. Chemical engineering journal 181 224
44. AAAI Conference on Artificial Intelligence 180 296
45. Journal of Materials Chemistry A 178 220
46. ACS Applied Materials & Interfaces 177 223
47. Nature Biotechnology 175 315
48. The Lancet Infectious Diseases 173 296
49. Frontiers in Immunology 173 228
50. Applied Energy 173 217
51. Nano Energy 172 232
52. Nature Energy 170 314
53. Meeting of the Association for Computational Linguistics (ACL) 169 304
54. The Astrophysical Journal 167 234
55. Gastroenterology 166 254
56. Nature Methods 165 296
57. IEEE Transactions on Pattern Analysis and Machine Intelligence 165 293
58. Cochrane Database of Systematic Reviews 165 243
59. Blood 165 229
60. Neuron 164 231
61. Nano Letters 164 207
62. Morbidity and Mortality Weekly Report 163 302
63. European Heart Journal 163 265
64. Nature Nanotechnology 163 264
65. ACS Catalysis 163 220
66. Nature Neuroscience 162 248
67. American Economic Review 160 263
68. Journal of High Energy Physics 160 220
69. IEEE Communications Surveys & Tutorials 159 304
70. Annals of Oncology 159 243
71. Nutrients 159 214
72. Accounts of Chemical Research 159 211
73. Immunity 158 242
74. Environmental Science & Technology 158 214
75. Nature Reviews. Molecular Cell Biology 155 340
76. Gut 155 235
77. Physical Review D 155 217
78. ACS Energy Letters 155 212
79. Monthly Notices of the Royal Astronomical Society 155 194
80. Conference on Empirical Methods in Natural Language Processing (EMNLP) 154 249
81. Clinical Infectious Diseases 153 278
82. Cell Metabolism 153 211
83. Nature Reviews Immunology 152 292
84. Joule 152 233
85. Nature Photonics 152 228
86. International Journal of Environmental Research and Public Health 152 225
87. Environmental Pollution 152 222
88. Computers in Human Behavior 152 214
89. Frontiers in Microbiology 151 225
90. Nature Physics 151 222
91. Small 150 196
92. Cell Reports 149 205
93. Molecular Cell 149 202
94. Clinical Cancer Research 146 201
95. Bioresource Technology 146 190
96. Journal of Business Research 145 233
97. Molecular Cancer 145 209
98. Sensors 145 201
99. Nature Climate Change 144 228
100. IEEE Internet of Things Journal 144 212